# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        dimensionVoiture: #nom du filtre
            quality: 90 #qualité de l'image
            filters:    #liste des filtres a appliquer
                upscale:
                    min: [500,320]  #taille de l'image de sortie
                thumbnail:
                    size: [500,320] #taille de l'image de sortie
                    mode: outbound  #découpage de l'image
                    

